### ISSUE TITLE
Project for Groups

### ISSUE THREAD

**Issue by biso93** [te-online/timemanager#1]
Hi, 
the application is pretty good, but it seem a bit limited for collaborate in teams.
It's possible tu add a Group association for the project? 
In this way i can input the Time Entries with my coworkes and the total time will be counted.

thanks

Francesco Bisognin

**Comment by te-online** [comment]
Hi @biso93 Thanks for trying the app! :-)
Indeed, adding collaboration/sharing is very high on my list of new features. While you're here, can I ask a few questions about how you'd prefer this feature to work?

- Would you be okay with just sharing a client and have all people you shared with have access to all subentities?
- Or would you need to be able to share just some projects of a client or just some tasks of a project? And if yes, why would it help you to have more granular sharing options?
- Would it help you to have permission controls? Like setting read-only or can-edit on a user/group you share with? If yes, how would it help your workflow to have that?

I can understand if you don't have time to answer those questions, but if you have, I'd be very happy to use your input to build the sharing feature 😊 

– Thomas

**Comment by biso93** [comment]
Hi @te-online, 
For my current experience with the app, the Client is the top level entity which the others is attached, so it's rasonable to share the Client across the group/team and Consequently the Project and the Tasks.

I usually create Projects and Tasks, and in my workflow i assign the task to a resposable, and for example he can or cannot re-assign to other (but i know, it's not very simple to implement i guess) when all the task is done, i can close the project, the team has visibility to the project and to all task, for my case everyone can collaborate, so granularity visibility on the task is a must have.

Globally in the Client for each project the read-only feature is more useful, for example a commercial task can be read from the helpdesk and each other, but they cannot edit each other.

i hope to helped you

Francesco Bisognin

**Comment by te-online** [comment]
@biso93 Perfect, thanks for your input! :-) I might come back with more questions and will keep this issue updated while sharing is being implemented.

**Comment by Terrox** [comment]
Is this the same as using built-in Nextcloud Projects instead of TimeManager's own project list?
https://docs.nextcloud.com/server/17/user_manual/files/projects.html
I'd prefer the projects to be the built-in NC ones although I haven't really thought about how that might clog up the Files/Deck workspace.

**Comment by te-online** [comment]
@Terrox Personally, I've never used Nextcloud Projects and I don't know how they work 😅 Another reason why I don't consider integrating with Nextcloud Projects a priority right now is that I feel like it would be quite a big task. However, that doesn't mean it's not a great idea. I just don't know anything about it :-)

**Comment by Terrox** [comment]
I think they are just tags really, I assume there's some API way to add/edit/query them so it would be a bit of learning curve and then easier than a custom coded method? total guesswork here.

**Comment by te-online** [comment]
I'll look into it when I get to this issue :-) But in the meantime, feel free to add any relevant info here that you find or open a PR if you're working on something already 🤓

**Comment by te-online** [comment]
@maltepost Thanks for adding your vote. 

However, let me be clear once again to avoid raising any big expectations: This is _not_ something that's on the roadmap right now. Unfortunately, if no help comes along, it has to wait. That's because it will require a major rewrite, since collaboration was not in the initial design of the database, controllers, API etc. (all of which are a bit older than they may look 😂). 

I'm sorry if this isn't the answer you were hoping for, but maybe the other app can give you what you need in the meantime – how ever long it will be.

**Comment by ikonnow** [comment]
> @maltepost Thanks for adding your vote.
> 
> However, let me be clear once again to avoid raising any big expectations: This is _not_ something that's on the roadmap right now. Unfortunately, if no help comes along, it has to wait. That's because it will require a major rewrite, since collaboration was not in the initial design of the database, controllers, API etc. (all of which are a bit older than they may look 😂).
> 
> I'm sorry if this isn't the answer you were hoping for, but maybe the other app can give you what you need in the meantime – how ever long it will be.

In my opinion and usage, **direct integration with the existing Nextcloud system is the most fundamental step** that would make TimeManager a tool for daily use. 

Since Deck is already an excellent multi-user project management application, TimeManager could be THE missing complement. The naming of tasks, as well as boards can be ideally used, linked and tracked. For the individual tasks, in addition to the date entry, a time recording can be integrated via e.g. just an icon. Furthermore, an automatic time recording can take place on the basis of the set date (however, this would also require a "complete" button, which is currently missing in the Deck Tasks).

Thanks for this nifty app i'm super excited to see what else comes of it!
There are requests in both repositories for exactly this feature(s) https://github.com/nextcloud/deck/issues/2299#issuecomment-737700705

**Comment by IanChok** [comment]
I think this feature is worth the time to re-work. This is the only feature needed for me to actually use the app.

**Comment by te-online** [comment]
Could you please check if basic sharing implemented in `v0.3.0 Beta` already covers your use-cases? 🙂

**Comment by biso93** [comment]
> Could you please check if basic sharing implemented in `v0.3.0 Beta` already covers your use-cases? 🙂

Basically yes! I just tried with my colleague and he can add time-entries in a shared customer.
