### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by escoand** [te-online/timemanager#108]
I'm not able to install TimeManager 0.3.4 on Nextcloud 25.0.2:

`
Database error when running migration 2006Date20211113102317 for app timemanager An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_timemanager_client' doesn't exist
`

**Comment by te-online** [comment]
Hey there – are you by any chance using PostgreSQL?

**Comment by escoand** [comment]
No sorry, I'm using MySQL.

**Comment by te-online** [comment]
Oh, well, first of all: I'm sorry you experience this!

Let's have a closer look.

1. So end-to-end tests for this repository run on `nextcloud:25-fpm-alpine`, which represents `25.0.2` as of now [according to DockerHub](https://hub.docker.com/_/nextcloud/). They're using `mariadb:10.5`. Are you using MariaDb?
2. The migration that fails is not the first or latest migration, so that's a bit random. It seems to fail to find the clients table, which coincidentally is the first table the migration works on. Can you see in your MySQL database that you indeed have no table ending in `timemanger_client`? Or any other `timemanager_*` tables?
3. Your prefix looks a bit strange too, it says `nextcloud.oc_` – is that your general database prefix for Nextcloud? You should be able to find your prefix in `config/config.php`. Maybe `nextcloud.` is just the database name? Then this would be the default.
4. In case you don't have any timemanager tables at all – I suspect the very first migration, which creates all tables, did not run (correctly) when you first installed the app. Can you try to remove it entirely (not sure if Nextcloud has a table with installed apps that you need to clean from it, or something) and reinstall?

Happy to hear your thoughts/answers on these points 😊

**Comment by te-online** [comment]
Since you haven't provided more information, I will close this issue for now. Please feel free to re-open if you have more details 😊
