### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by R7JANV1** [te-online/timemanager#112]
With the latest update, this error occurs when using Nextcloud AIO.
Nextcloud AIO; stable

**Comment by te-online** [comment]
Hey there 👋 Thanks for reporting this issue. 

Can you provide some more information, so I can investigate? What's your Nextcloud setup? Server OS, Nextcloud version, database type and version? 

Are you using PostgreSQL by any chance? Then you might be running into this issue, which will be fixed with the next release: #100

**Comment by R7JANV1** [comment]
Yes i usw PostgreSQL... perfect thank you!
