### ISSUE TITLE
Nextcloud 26 compatibility

### ISSUE THREAD

**Issue by elpraga** [te-online/timemanager#117]
Thank you @te-online for your app!

Are you planning to release a Nextcloud 26 compatible version?

**Comment by WhoAmI0501** [comment]
I currently debugged, why the timemanager app is not working with v26.

Its because the `OCP\AppFramework\Db\Mapper` in Nextcloud is deprecated (since v14?) and was now removed. Instead of the obsolete Mapper, `OCP\AppFramework\Db\QBMapper` should be used.

This actually means, that all SQL statements have to be rewritten for the new QBMapper, since statements are not passed anymore as a string. For more information, see the [developer docs](https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/database.html). This looks like a big bunch of work.


You need a very dirty, temporary workaround? Here we go. Download the latest Nextcloud v25 Release from GitHub and copy the old Mapper (can be found under `lib/public/AppFramework/Db/Mapper.php`) and place it at the same location in your Nextcloud v26 installation. Make sure, that the filesystem permissions are correct. Further, my Nextcloud docker container needed a restart.
You will do that on your own risk. This works on my machine, but may break your machine. I do not support or recommend this "solution" in any way.

**Comment by te-online** [comment]
Should be fixed in 0.3.7 Beta
