### ISSUE TITLE
Timemanager using on NC 27

### ISSUE THREAD

**Issue by strobobaer** [te-online/timemanager#130]
Hello we need to update 
is Timemanager running on NC27?? soon

**Comment by te-online** [comment]
Hi @strobobaer Thanks for opening this issue. I'm pinning this, because this question will probably be repeated by others.

As Nextcloud 27 has been released yesterday I will now start the process of updating the app for this version. You can expect this to take a few days or weeks, depending on the amount of adjustments needed. I'm sorry if this is not what you were hoping for. 

If you run Nextcloud in production and you subscribe to the "stable" channel you can almost always be sure that my apps will have updates available once you get prompted to update your Nextcloud.

Additionally, check for the section that tells you about app compatibility before upgrading your Nextcloud. There is a section "Apps missing compatible versions" if you have apps installed that are not compatible with the next version of Nextcloud.

![Screenshot 2023-06-14 at 20 25 13](https://github.com/te-online/files_linkeditor/assets/4127167/dc96bb42-f161-4615-8c0d-20589cbf3419)

**Comment by te-online** [comment]
I think you may have missed some information in my above post 😊 

> As Nextcloud 27 has been released yesterday I will now start the process of updating the app for this version. You can expect this to take a few days or weeks, depending on the amount of adjustments needed. I'm sorry if this is not what you were hoping for.

This app currently not compatible with Nextcloud 27, that's why it's not working.

**Comment by WhoAmI0501** [comment]
Yep - sorry. Thats why I edited my post afterwards - but i though its better to leave the error message here, as it may helps you at debugging. Thanks for your work! :)

**Comment by Uatschitchun** [comment]
Would love to use it ;)

**Comment by leachimus** [comment]
I hope you manage to adjust that soon. Thanks a lot! 🙋🏼‍♂️

**Comment by te-online** [comment]
Please try version 0.3.8 that just landed in the AppStore!

Thanks to @SpaceCafe we should have support for Nextcloud 27 now 🎉
