### ISSUE TITLE
Adding Time entries without a task

### ISSUE THREAD

**Issue by gerhardbeck** [te-online/timemanager#136]
I just tried to add some times, but it didn't work without a task.
In #91 I noticed the problem.

two suggestions:
a) a hint that a task is necessary would be useful
b) I would suggest a possibility to add time entries without a task, just by selecting the project.

In my work it's not all specified by tasks I know before starting, therefore this way is quite useless and more a problem...

**Comment by te-online** [comment]
Yes, I fully agree and this is something that's going to be added in the future 😊 

Keep an eye on #89 to see the progress.

In terms of b) I'm still undecided, because it will be a bit of a challenge to design, technically. But I can see an option where the app would ship with a default client, project and task – just to get you started.

I'll close this in favor of the other existing issue(s).
