### ISSUE TITLE
Tools page not translated to French

### ISSUE THREAD

**Issue by punkyard** [te-online/timemanager#155]
<img width="1354" alt="Capture d’écran 2024-01-15 à 23 31 29" src="https://github.com/te-online/timemanager/assets/59349105/0225e9bf-a0d5-46a1-8b12-bede074df40e">

Hi
We're using Time Manager in French
It's all translated correctly BUT the tools menu

Is help required to translate it?
Is it a bug?

**Comment by te-online** [comment]
Yes! 😊 If you'd like to add translations, you'd need to fork this repository and edit 

- [this JSON file](https://github.com/te-online/timemanager/blob/main/l10n/fr.json)
- [and this JS file](https://github.com/te-online/timemanager/blob/main/l10n/fr.js)

Then open a PR with your changes and I will happily include it in the next release.

Transifex is not yet set up for this repository due to the large overhead, but I'm still considering it.

If you're looking for the missing strings, check out [this file](https://github.com/te-online/timemanager/blob/main/l10n/de_DE.json), it should be complete.

**Comment by punkyard** [comment]
yes, I'll try a fork
I'm a user and active collaborator for issues and suggestions, but I don't know yet how to have a more technical usage of git

**Comment by te-online** [comment]
> yes, I'll try a fork
> I'm a user and active collaborator for issues and suggestions, but I don't know yet how to have a more technical usage of git

Great 😊 I believe you can come pretty far by just using the Github.com UI to edit files and commit your changes. Wish you luck

> are the two json flies supposed to be exactly alike?

Yes, there is one `json` file, which is consumed by the server and one `js` (JavaScript) file, which is used on the frontend. The strings should be exactly the same in both of them, but the format is slightly different. But don't worry too much about the format, I can fix that up later if something is wrong.

**Comment by punkyard** [comment]
Hi
I had to do the 'commit' twice to see it appear in my own account.
Will you please confirm that I've done it right with the two files?

I'm really happy to contribute this way :)

**Comment by te-online** [comment]
Thanks for your contribution! 🎉 Your translations will be in the next release; not more than a couple of weeks, hopefully 🙏

**Comment by punkyard** [comment]
one final note about the 'wording'?
I have translated 'Tools' to French as 'Outils'
but in this case, wouldn't it be clearer for simple users to read 'Import' (same in French) instead of 'tools' for this section?

**Comment by te-online** [comment]
Yes, I think you have a good point. The idea was that at some point you could do more on this page, i.e. it would include more tools than just "Import". But that's not happened, so we might as well rename it. If you want to can adjust your translation and create a new PR, otherwise you can wait until I will eventually rename it or put more tools on the page 😆
