### ISSUE TITLE
Navbar icons don't show up when using https

### ISSUE THREAD

**Issue by miku86** [te-online/timemanager#16]
Hey Thomas,

thanks for your app!

When I load the app, the icons of the navbar don't show up.

Looking into the Dev Tool DOM, I can see that the img links go to `http`, but my Nextcloud instance uses `https`.

When I change `http` to `https` in the DOM, all icons work just fine.

Seems to come from this file: https://github.com/te-online/timemanager/blob/b3dceaa0ade8b3bf067de23228415d95998c1f8e/templates/partials/navigation.php

Unfortunately, I'm not into PHP and can't test if this can get fixed by some code changes or if this is caused by my instance somehow.

Thanks
Michael

**Comment by te-online** [comment]
Hey @miku86 :-) Thanks for opening an issue because of missing navbar icons. Can I ask which Nextcloud version you're using? The navigation uses Nextcloud's default URL generator, so it should know that your Nextcloud is running https. Maybe you're missing a setting in your `config/config.php`? https://github.com/nextcloud/server/blob/master/config/config.sample.php#L474

**Comment by miku86** [comment]
Hey @te-online,

I set `'overwriteprotocol'` to `'https'` and it is now working as expected. :slightly_smiling_face: 

Thank you
Michael
