### ISSUE TITLE
Time tracking entry not visible for shares

### ISSUE THREAD

**Issue by syntaxys** [te-online/timemanager#162]
![shared-time](https://github.com/te-online/timemanager/assets/666672/e56a66d2-1e14-46a6-81a7-66a68083257f)

When I share the time tracking of a project with a customer, he sees the shared projects and tasks, but not the times that I have tracked.
It is also not possible for the customer to create a report for these tracked times.

- Nextcloud 28.0.3
- MySQL 8.0.36-0ubuntu0.22.04.1
- TimeManager 0.3.11

**Comment by te-online** [comment]
Hello 👋 Thanks for reporting.

Unfortunately, I don't have good news for you, as this is by design. The sharing feature is meant to be used within a team. Whoever manages the time entries for a team can share their client with other team members. Those member can then enter their times and it will be visible to the sharer, but not to other people in the team.

For sharing entries with a client, I can only suggest to create a report and send that one to the client.

Sorry if this doesn't help you... 😿 

![grafik](https://github.com/te-online/timemanager/assets/4127167/b551185b-f921-4ce9-b835-5cff4c8c5607)
