### ISSUE TITLE
No info displayed in Android app

### ISSUE THREAD

**Issue by Gene-W** [te-online/timemanager#182]
Very much like #148 Android app isn't showing any information for me. I've cleared cache, rebooted, checked for updates but still not showing anything. My NC is hosted on Hetzner, no updates available there either.

**Comment by te-online** [comment]
Hey 👋  I'm sorry the Android app doesn't work. It's very hard for me to reproduce those kinds of issues, because I don't have an Android phone handy and I have never used the app.

There haven't been any changes to the API, so the app should work just as it did before.

Therefore a few questions:
- Did this every work for you?
- I assume you're using Nextcloud 29.0.3 and TimeManager 0.3.14?
- Is there anything about TimeManager or similar in your Nextcloud logs (Click on your user avatar in the top right corner, then -> Administration settings -> Logging)?

**Comment by Gene-W** [comment]
Hi and thanks for your reply!
Here's a little more information but I feel like I can't find enough to be helpful:

- It has worked very well previously, last used about a week ago. Also, TimeManager is working fine in my browser, just not on the Android app.
- Using NC 27.1.10 (Hetzner is managed but affordable) TimeManager 0.3.14
- Logs - I can't seem to find access to these. I've checked in my NC admin settings and in my Hetzner account. Another burden of hosted NC I guess.

**Comment by Werbegams** [comment]
Hy, I am faci g the same problem.
First it worked fine on NC 27 for over 6 month, than the first android phone got no data from the server.
Then i updated NC to 29 and all timemanager apps to the latest version.
Now no android phone or tablet get any data from the server.
I can create a new customer, but as soon as I close the app and reopen it, nothing is displayed.
In the past we allready had this problem and if i remember me corectly, it was somethi g with a query limit!?

In the NC loggs is nothing with an Error of timemanager, and I think it is really no error but a limit in the app wich runs into the described problem.

Phone: Samsung android 14
Tablet: Lenovo android 11

**Comment by te-online** [comment]
Hi 🙂 I'm sorry the Android app is not working. There isn't much I can do to fix it right away.

The limit you talk about is not something that is built into the app in any form or shape. It was a limitation of using the more modern database layer, which has since been rolled back. Since you're using the latest version of both TimeManager in your Nextcloud as well as the Android app, you shouldn't be affected by that particular issue. Additionally, in that case you'd see errors in your log.

Maybe a bug was introduced in the latest Android app release, if you say that you updated recently? I see there is [an issue on the Gitlab repository](https://gitlab.com/joleaf/nc-timemanager-mobile-app/-/issues/17).

Could there be a way for you to install an earlier version of the Android app [through the Play store](https://play.google.com/store/apps/details/Nextcloud_Timemanager?id=de.jbservices.nc_timemanager_app&hl=en_US)? I'm not sure if that's possible?

**Comment by Gene-W** [comment]
Thank you for this information, I mistakenly didn't realize the Android app was entirely different. I don't use Play Store Services but I'll try to find the previous APK and give that a try.

**Comment by Werbegams** [comment]
Hy,
I just found a solution which worked for me.
Just for the information: I updated my android phone after the problem occured, because I thought, maybe there is a problem.
Now I installed an older version of Timemanager (Nextcloud Timemanager 21.12.0) from APKPure (https://apkpure.com/de/nextcloud-timemanager/de.jbservices.nc_timemanager_app/download/21.12.0)
This solved the troubles on all devices (Smartphone and Tablet)

**Comment by te-online** [comment]
Great 👍 

Also check out [this issue](https://gitlab.com/joleaf/nc-timemanager-mobile-app/-/issues/17) where a contributor is actively addressing the issue in the Android app. 

I guess anyone can help testing, if they're up for it 😊

**Comment by Gene-W** [comment]
I've also moved to the older version until an update is available. Thanks for the assistance!
