### ISSUE TITLE
 Merge with timetracker and volunteer

### ISSUE THREAD

**Issue by torstendoerschel** [te-online/timemanager#22]
Hi there,
it seems there are two nextcloud apps being developed with the same goal:
[https://github.com/mtierltd/timetracker](url) and [https://github.com/te-online/timemanager/](url)
 
Timetracker, despite early stage, already has the grounds for multiple user (and group) interaction.
Time Manager seems to have a better interface, but is still very limited (single user, many clicks to create a single entry etc.)

It seems to me if both projects join forces a great app can come out of it.

I have no experience in NC app development so far, but I wanted to learn about it in order to develop a time tracking app inspired by www.goodtimetracking.com
Have you had a look at the other app and chatted with the contributor/owner about merging?
How can I help you?

Have a Happy New Year!
Torsten

**Comment by te-online** [comment]
@torstendoerschel, thanks for your helpful comment. I've not had the chance to talk to the maintainer of timetracker, but have tried it on my own Nextcloud once. 

I really don't see it as a competition – in my world both apps can co-exist. Some things might be better/easier/prettier in one app, some in the other. 

You mention group features: This app was never designed to have support for multi-user scenarios. It's just something I started a long time ago as a tool for myself and published it just recently. I'm sorry if I disappoint your expectations here, but that's the current status.

So, this might just be the main distinguishing factor between the two apps. If you want multi-user support, make sure to consider investing your time in timetracker. Maybe polishing its UI will be faster than adding a sane sharing backend to timemanager.

In regards to how you could help this project: Have a look at what people have been wishing for in the issue list on this Github repo and consider your own wishes. Start with something either really small or something that really bugs you and open your first Pull Request. There's no roadmap or anything like that, so anything is fine to start working on.

Sorry if this is not the answer you were looking for – very much appreciate your support and if you have anything you'd like to change or contribute, always feel free to open a PR, as I said, even if it's a work-in-progress. Maybe I can then help with a few pointers in the right direction.

----

PS: I'm curious how we could minimize the number of clicks to create a single entry. Personally, I use the quick-add on the Dashboard (the one of TimeManager, not the new Nextcloud Dashboard) and I solely use it with my keyboard. That's why I have no idea about the number of clicks needed 😄 Feel free to open up a new issue on reducing the number of clicks needed to create a single entry or anything else you find important.

----

I'm going to close this, because there are currently no plans to merge with TimeTracker.
