### ISSUE TITLE
Tasks seperated from clients

### ISSUE THREAD

**Issue by hurgar-nl** [te-online/timemanager#56]
Hi, first of all, I really like your app. I am using it right now!
There is one thing that I think would improve the app, and that is seperating the tasks from the clients. 
Because I do the same tasks for mulitple clients. And adding the same tasks for each new client seems a bit overboard imho.

Thank you again for this great app, and keep up the good work!
With regards, Arno

**Comment by te-online** [comment]
Hey there 👋 Thanks for your feedback. I can see how this would be use-case for some users!

However, I'm afraid I have to manage expectations here, as with many other features, and I hope you understand: This is not something that's on my personal roadmap right now. Unfortunately, if no help comes along, it has to wait. That's because it will require some major changes, as tasks are generally children of projects and projects are generally children of clients. 

Everyone is of course welcome to contribute by diving into the code and creating a PR.

I'm sorry if this isn't the answer you were hoping for 😞 

One idea could be to create a template feature, so you can create all the tasks you'd like with a click of a button. Would that work for your use-case? 🤔

**Comment by hurgar-nl** [comment]
Hi Thomas,

Thank you for your reply and your idea of creating a template. I will look into that!
I will also look into the code, but as I have no previous experience with creating apps for nextcloud I am afraid I cannot help in that area. But who knows?

With regards,
Arno

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
