### ISSUE TITLE
Detailed list of entries per client

### ISSUE THREAD

**Issue by dbvcode** [te-online/timemanager#7]
Hello and congrats for this project!
It's exactly what I need right now to track some work for a client. Got used to it and put in about 4 days of work.

What would be very nice is to see a detailed list from start date to end date for a specific client with all the work done for them.

This could be useful to mail it to the client or attach it to the invoice.
Any plans on adding such features? Maybe even an export function along the lines I've mentioned?
Unfortunately I have 0 php skills so I cannot help here. :(

Cheers and keep up the good work,
DBV

**Comment by te-online** [comment]
Hey @dbvcode thanks for your kind words and interest in the app :-)

I'd suggest we'll have some sort of Reporting feature at some point that'll cover your needed functionality. At this moment the next feature to be implemented will be group collaboration, however. But I'll mark this as feature request and since I miss this functionality too, I think this should be the next feature after that. If you have any more input like a feature description or some scribbles for the needed UI, feel free to add them here :-)

**Comment by te-online** [comment]
Please check out [version 0.2.0](https://github.com/te-online/timemanager/releases/tag/v0.2.0) for a reporting feature that addresses this feature request ✨
