### ISSUE TITLE
Allow sharees to edit / be admin of shared client

### ISSUE THREAD

**Issue by tsenegas** [te-online/timemanager#78]
Hey,

I would love to be able to share a client with other users but not as read-only. So we could be two admins for examples for a client and both able to take a look a the whole reports and time entries for a client.

Thanks

**Comment by te-online** [comment]
Hey @tsenegas 👋 

Thanks for taking the time to open an issue. This is indeed a nice feature, but it's a bit complicated to implement, since it requires a whole lot of changes and some UX work. 

Since now we have the new sharing feature, there is a chance though that this will be added at some point. I have no timeline for you right now, unfortunately.

If you'd like to contribute to this feature you are more than welcome to do so 🤓

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
