### ISSUE TITLE
.1 hours can not be entered

### ISSUE THREAD

**Issue by Andyj9** [te-online/timemanager#9]
Trying to set billing to .1 hr - input only allows min .25.
This should be changed to .1 - that is 1/10 of an hour or 6 minutes.
Allows fine reporting to our clients.

**Comment by te-online** [comment]
Thanks for opening an issue about that. Actually, that's a deliberate decision to simplify the user interface. 😊 

I do see that some businesses rather track in 1, 5 or 10 minute steps. But in my opinion, hours cannot be split in more than 4 different tasks, that's sort of unrealistic, unless your tasks are specifically designed to be very, very short.

So, while I can imagine lowering the interval, I'm not sure about it right now 🤔 What if you prepare a pull request for this change? 😄

**Comment by Crazy-Sonic** [comment]
I am also for it, since we also calculate in 0.1h.
Maybe it makes sense to set the time to 0.05. This helps everyone to enter their times correctly. :-)

**Comment by TheTimeWalker** [comment]
Hey, seeing as this is a deliberate action, I've been wondering what makes it "simpler"? Coming from something like Clockify and Vertec, it seems pretty fine for me that the user interface shows your hours as xx:xx e.g. 3:15 instead of 3.25h. IMO, I find it a bit more weird to see it as ".xx" as it seems a bit unnatural to see 3.75 instead of 3:45 hours. I agree that in that case when you have somebody using .10 intervals, it would get pretty messy.

With regard to an hour can be split into four tasks, I think the issue is that some companies most likely want very fine-grained reporting and not that you have like 8 tasks in one hour. 😅 It's possible that somebody would work on Task 1 for 5:40 hours and then Task 2 for 2:20 hours totaling 8 hours. Or maybe it's a short visit to a client and you've been doing a task for 1:05 hours so you can bill them appropriately.

I would propose that the layout would be changed from a decimal number to a more natural time layout. This would also solve this issue as people can use any minute steps if they wish for without taking a hit from readability. Maybe we could also implement time rounding per project so everybody with company guidelines to personal reasons can be happy. 😄

**Comment by te-online** [comment]
@TheTimeWalker thanks for taking the time to make some valid and valuable points. It's not so much that I want to enforce my strong opinion, but that functionality has previously we been built with my workflow in mind. While I'm aware that this doesn't fit for everyone I want to keep it simple for everyone 🙂

I'd love to respond to your points in detail, but right now I can't. That doesn't mean that I'm going to reject a PR or draft of a PR that follows a reasonable approach like you outlined. Feel free to chime in as long as I don't have time to take care of it, it won't be time wasted 😉

**Comment by te-online** [comment]
The latest release (`0.1.5 Beta`) features a `0.01` step setting for time entries, so you should be able to enter 0.1 time entries now. However, I'd also like an option of entering the time more naturally for folks who prefer that. This is being handled in a new issue #18.
