### ISSUE TITLE
Cannot select client from dropdown

### ISSUE THREAD

**Issue by aprile007** [te-online/timemanager#91]
Hi, 
I just installed Time manager and this looks like a very promising app.
although when i add a client i am not able to add them when trying to input data in the dashboard section.
When i type the name of the client it does return a result but i cannot select it.

next cloud is snap version 24.0.4
I am using FF but also tried with brave

thanks.

![image](https://user-images.githubusercontent.com/33985191/193470050-0c1197ae-b9a5-40a1-9515-78bddeabea50.png)

**Comment by te-online** [comment]
Hey there @aprile007 👋 

Thanks for trying the app and opening an issue.

I'm sorry to tell you that this is by design 😞 

You can only track time on tasks. And tasks need to be created on projects and projects on clients. This is why you can't select a client to create a time entry on.

I have plans to add a "Add task" button to the bottom of the search popover, though. See #89. This would enable users to create a client, project or task without leaving the quick-add flow.
